name: CI-workflow

on: 
  pull_request:
  push:
    branches:
      - develop

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Update Shellcheck
        run: chmod +x scripts/download_shellcheck.sh && ./scripts/download_shellcheck.sh
      - name: Run tests
        run: ./tests/test_runner
        shell: bash
    

